FROM adoptopenjdk:11-jre-hotspot

ENV SPRING_DATASOURCE_URL=${DB_COURSE_URL}
ENV SPRING_DATASOURCE_USERNAME=${DB_COURSE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${DB_COURSE_PASSWORD}

# Set environment variables for Eureka server
ENV EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=https

ENV JWT_SECRET_KEY=secret
ENV JWT_SERVICE_SECRET=secret-service
ENV JWT_EXPIRES_TIME=1000
# Set environment variables for Cloudinary
ENV CLOUDINARY_NAME=${CLOUD_NAME}
ENV CLOUDINARY_API_KEY=${CLOUD_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUD_API_SECRET}
ENV CLOUDINARY_WATERMARK=${CLOUD_WARTERMARK}
ENV ALLOWED_CONTENT_TYPES=image/jpeg,image/png,application/pdf,image/gif,video/mp4

# Set environment variables for Send mail
ENV SPRING_MAIL_HOST=smtp.gmail.com
ENV SPRING_MAIL_PORT=587
ENV SPRING_MAIL_USERNAME=${EMAIL_USERNAME}
ENV SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD}

ENV METHOD=https

ENV VNPAY_RETURN_URL=http://localhost:8084/check-transaction
ENV VNPAY_REDIRECT_URL=https://capstone-fe-woad.vercel.app/my-course
ENV VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
ENV VNP_TMNCODE=${VNP_TMNCODE}

VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY ./target/courseservice-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
